/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Persistencia.ManejoArchivoTexto;
import Utilidades.ArchivoTexto;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    ManejoArchivoTexto archi = new ManejoArchivoTexto();
    ArchivoTexto archivo = new ArchivoTexto();
    DefaultTableModel modelo;
    ArchivoTexto datos = new ArchivoTexto();
    File fichero;
    
    /*void asignarDatos(int n, String isbn,String titulo, String autor, int nPaginas, int edicion, double peso, double duracion, String formato, double costo){
    
        try {
            if(n==1){
                BufferedWriter fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(fichero, true)));
                fescribe.write(n+"      "+isbn+"        "+titulo+"                          "+autor+"                             "+nPaginas+"          "+edicion+"       "+peso+"         "+duracion+"         "+formato+"       "+costo+"  ");
                fescribe.write("\n");
                System.out.println("El libro fue insertado correctamente");
                fescribe.close();
                
            }if (n==2){
                BufferedWriter fescribe = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(fichero, true)));
                fescribe.write(n+"       "+isbn+"        "+titulo+"                          "+autor+"                             "+nPaginas+"          "+edicion+"         "+peso+"       "+duracion+"         "+formato+"       "+costo+" ");
                //System.err.printf("%-15s","%-15s","%-15s","%-15s","%-15s","%-15s","%-15s","%-15s",isbn,titulo,autor,nPaginas,edicion,peso,duracion,formato);
                fescribe.write("\n");
                System.out.println("El libro fue insertado correctamente");
                fescribe.close();
            }
            
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }*/
    
    //"TIPO", "ISBN", "TITULO", "AUTOR", "NO PAG", "EDICION", "PESO", "DURACION", "FORMATO");
    public Interfaz() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_HORIZ);
        modelo = new DefaultTableModel();
        modelo.addColumn("TIPO");
        modelo.addColumn("ISBN");
        modelo.addColumn("TITULO");
        modelo.addColumn("AUTOR");
        modelo.addColumn("N* PAGINAS");
        modelo.addColumn("EDICION");
        modelo.addColumn("PESO");
        modelo.addColumn("DURACION");
        modelo.addColumn("FORMATO");
        modelo.addColumn("COSTO");
        
        this.tabla.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoIsbn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoAutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        selectLIBRO = new javax.swing.JRadioButton();
        CampoCosto = new javax.swing.JTextField();
        selectAUDIOLIBRO = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoNPAGINAS = new javax.swing.JTextField();
        campoEDICION = new javax.swing.JTextField();
        campoDURACION = new javax.swing.JTextField();
        campoPESO = new javax.swing.JTextField();
        campoFORMATO = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        BuscarLibro = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("ISBN:");

        campoIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIsbnActionPerformed(evt);
            }
        });

        jLabel2.setText("TITULO:");

        jLabel3.setText("AUTOR:");

        jLabel4.setText("AÑO:");

        campoAño.setText("2022");
        campoAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAñoActionPerformed(evt);
            }
        });

        jLabel5.setText("COSTO:");

        buttonGroup1.add(selectLIBRO);
        selectLIBRO.setSelected(true);
        selectLIBRO.setText("1. LIBRO");
        selectLIBRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectLIBROMouseClicked(evt);
            }
        });
        selectLIBRO.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                selectLIBROCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        selectLIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLIBROActionPerformed(evt);
            }
        });

        CampoCosto.setText("0");
        CampoCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCostoActionPerformed(evt);
            }
        });

        buttonGroup1.add(selectAUDIOLIBRO);
        selectAUDIOLIBRO.setText("2. AUDIO LIBRO");
        selectAUDIOLIBRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectAUDIOLIBROMouseClicked(evt);
            }
        });
        selectAUDIOLIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAUDIOLIBROActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("N* PAGINAS:");

        jLabel8.setText("EDICION:");

        jLabel9.setText("DURACION:");

        jLabel10.setText("PESO: ");

        jLabel11.setText("FORMATO:");

        campoNPAGINAS.setText("0");

        campoEDICION.setText("0");
        campoEDICION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEDICIONActionPerformed(evt);
            }
        });

        campoDURACION.setText("0");
        campoDURACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDURACIONActionPerformed(evt);
            }
        });

        campoPESO.setText("0");

        campoFORMATO.setEditable(true);
        campoFORMATO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MP3", "ACC", "WAV", "AC3", "AIF", "OGG" }));
        campoFORMATO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFORMATOActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("REGISTRO DE LIBRO");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoAutor)
                                            .addComponent(campoAño)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CampoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNPAGINAS)
                            .addComponent(campoEDICION)
                            .addComponent(campoDURACION)
                            .addComponent(campoPESO)
                            .addComponent(campoFORMATO, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectAUDIOLIBRO)
                            .addComponent(btnCancelar))
                        .addGap(219, 219, 219)))
                .addGap(58, 183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(campoNPAGINAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(campoEDICION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoDURACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoPESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(campoFORMATO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectLIBRO)
                    .addComponent(selectAUDIOLIBRO))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("jLabel12");

        jMenu7.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setText("Mostrar Libros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        BuscarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        BuscarLibro.setText("Buscar Libro");
        BuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarLibroActionPerformed(evt);
            }
        });
        jMenu7.add(BuscarLibro);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MostrarLibros consulta = new MostrarLibros();
        escritorio.add(consulta);
        consulta.show();
        //consulta.agregar();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void campoFORMATOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFORMATOActionPerformed
        // TODO add your handling code here:
        String mensaje = "";
        mensaje = mensaje+campoFORMATO.getSelectedItem().toString();
    }//GEN-LAST:event_campoFORMATOActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
        String isbn; 
        isbn =campoIsbn.getText();
        String titulo = "NA"; 
        titulo = campoTitulo.getText();
        String autor = "NA";
        autor = campoAutor.getText();
        double año;
        año = Double.parseDouble(campoAño.getText());
        double costo;
        costo = Double.parseDouble(CampoCosto.getText());
        
        campoIsbn.requestFocus();
        
        
        if(archivo.getOpcion1()==1){
            double npagina;
            npagina = Double.parseDouble(campoNPAGINAS.getText());
            double edicion;
            edicion = Double.parseDouble(campoEDICION.getText());
            int resultadoDlg = JOptionPane.showConfirmDialog(this, "DESEA GUARDAR ESTE LIBRO?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
            
            if ((resultadoDlg==JOptionPane.YES_OPTION)){
            archi.CrearArchivo();
            archi.AsignarDatos(archivo.getOpcion1(), isbn, titulo, autor, (int)año, costo, (int)npagina, (int)edicion, 0, 0, "NA");
            modelo.addRow(new Object[] {
            archivo.getOpcion1(), isbn, titulo, autor, (int)npagina, edicion,0,0, "NA",costo 
    });
            JOptionPane.showMessageDialog(this, "LIBRO GUARDADO", "", JOptionPane.INFORMATION_MESSAGE);
            }   
        
        }
        if(archivo.getOpcion1()==2){
            double duracion;
            duracion = Double.parseDouble(campoDURACION.getText());
            double peso;
            peso = Double.parseDouble(campoPESO.getText());
            String formato = "NA";
            formato = campoFORMATO.getSelectedItem().toString();
            int resultadoDlg = JOptionPane.showConfirmDialog(this, "DESEA GUARDAR ESTE LIBRO?", "CONFIRMACION", JOptionPane.YES_NO_OPTION);
            if (resultadoDlg==JOptionPane.YES_OPTION){
            archi.CrearArchivo();
            archi.AsignarDatos(archivo.getOpcion1(), isbn, titulo, autor, (int)año, costo, 0, 0, duracion, peso, formato);
            modelo.addRow(new Object[] {
            archivo.getOpcion1(), isbn, titulo, autor, 0, 0, peso, duracion, formato,costo
    });
            JOptionPane.showMessageDialog(this, "LIBRO GUARDADO", "", JOptionPane.INFORMATION_MESSAGE);
        }
        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "MAL CAPTURA DE DATOS", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            campoIsbn.requestFocus();
        } 

    }//GEN-LAST:event_btnGuardarActionPerformed
    //"TIPO", "ISBN", "TITULO", "AUTOR", "NO PAG", "EDICION", "PESO", "DURACION", "FORMATO");
    private void selectAUDIOLIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAUDIOLIBROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectAUDIOLIBROActionPerformed

    private void selectAUDIOLIBROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectAUDIOLIBROMouseClicked
        // TODO add your handling code here:
        archivo.setOpcion1(2);
    }//GEN-LAST:event_selectAUDIOLIBROMouseClicked

    private void selectLIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLIBROActionPerformed
        // TODO add your handling code here:
        campoAño.setText("2022");
    }//GEN-LAST:event_selectLIBROActionPerformed

    private void selectLIBROCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_selectLIBROCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectLIBROCaretPositionChanged

    private void selectLIBROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectLIBROMouseClicked
        // TODO add your handling code here:

        archivo.setOpcion1(1);

    }//GEN-LAST:event_selectLIBROMouseClicked

    private void campoIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIsbnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoIsbnActionPerformed

    private void campoAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAñoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoAñoActionPerformed

    private void CampoCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCostoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CampoCostoActionPerformed

    private void campoEDICIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEDICIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEDICIONActionPerformed

    private void BuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarLibroActionPerformed
        // TODO add your handling code here:
        BuscarLibro buscar = new BuscarLibro();
        escritorio.add(buscar);
        buscar.show();

    }//GEN-LAST:event_BuscarLibroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        campoIsbn.setText("");
        campoTitulo.setText("");
        campoAutor.setText("");
        campoAño.setText("2022");
        CampoCosto.setText("0");
        campoNPAGINAS.setText("0");
        campoEDICION.setText("0");
        campoDURACION.setText("0");
        campoPESO.setText("0");
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void campoDURACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDURACIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDURACIONActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuscarLibro;
    private javax.swing.JTextField CampoCosto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JTextField campoAño;
    private javax.swing.JTextField campoDURACION;
    private javax.swing.JTextField campoEDICION;
    public javax.swing.JComboBox<String> campoFORMATO;
    private javax.swing.JTextField campoIsbn;
    private javax.swing.JTextField campoNPAGINAS;
    private javax.swing.JTextField campoPESO;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton selectAUDIOLIBRO;
    private javax.swing.JRadioButton selectLIBRO;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
