/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Persistencia.ManejoArchivoTexto;
import Utilidades.ArchivoTexto;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import Vista.Main.*;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class MostrarLibros extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ArchivoTexto datos = new ArchivoTexto();
    Interfaz i;
    DefaultTableModel modelo;
    ManejoArchivoTexto manejo = new ManejoArchivoTexto();
    
    public MostrarLibros() {
        initComponents();
        String[] titulo = new String[]{"TIPO","ISBN","TITULO","AUTOR","NO PAG", "EDICION", "PESO", "DURACION", "FORMATO"};
        dtm.setColumnIdentifiers(titulo);
        //TableLibros.setModel(dtm);
        agregar();
        modelo = new DefaultTableModel();
        modelo.addColumn("TIPO         ISBN        TITULO          AUTOR                 N* PAGINA         EDICION         PESO         DURACION         FORMATO     COSTO");
         
        this.Tbla.setModel(modelo);
    }
    void agregar(){
        
        dtm.addRow(new Object[]{
            datos.getOpcion1(),datos.getIdbn(),datos.getTitulo(),datos.getAutor(),datos.getnPaginas(),datos.getEdicion(),
            datos.getPeso(),datos.getDuracion(),datos.getFormato()
        });
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Tbla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mostrar = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CONSULTA LIBROS");

        Tbla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(Tbla);

        mostrar.setText("Mostrar");
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
        });
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jMenuBar1.add(mostrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        //agregar();
        try {
            
           //System.out.printf("%-10s %-10s %-30s %-30s %-10s %-10s %-10s %-10s %-10s%n", "TIPO", "ISBN", "TITULO", "AUTOR", "NO PAG", "EDICION", "PESO", "DURACION", "FORMATO");
           //System.out.println("----------------------------------------");
           FileReader fr = new FileReader("Libros.txt");
           BufferedReader br = new BufferedReader(fr);
           String cadena;
           while((cadena=br.readLine())!=null){
               //jTextArea1.setText(String.valueOf(cadena));
               System.out.println(cadena);
           }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_mostrarActionPerformed

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked
        // TODO add your handling code here:
        //agregar();
        
        try {
            
           //System.out.printf("%-10s %-10s %-30s %-30s %-10s %-10s %-10s %-10s %-10s%n", "TIPO", "ISBN", "TITULO", "AUTOR", "NO PAG", "EDICION", "PESO", "DURACION", "FORMATO");
           //System.out.println("----------------------------------------");
           FileReader fr = new FileReader("Libros.txt");
           BufferedReader br = new BufferedReader(fr);
           String cadena;
           while((cadena=br.readLine())!=null){
               modelo.addRow(new Object[]{
                   cadena
               });
            /*if((cadena=br.readLine())==null){
                JOptionPane.showMessageDialog(this,"NO HAY LIBROS", "", JOptionPane.INFORMATION_MESSAGE);
           }*/
           }
               
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mostrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbla;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mostrar;
    // End of variables declaration//GEN-END:variables
}
